
### Requição dos dados da tabela user 


curl -X GET http://localhost:3000/users


### Requisição de Registro

curl -X POST http://localhost:3000/register -H "Content-Type: application/json" -d '{"name": "Jeremias", "email": "Jeremias@example.com", "password": "senhaSeguraa"}'

### Requisição de login


curl -X POST http://localhost:3000/login -H "Content-Type: application/json" -d '{"email": "Jeremias@example.com", "password": "senhaSeguraa"}'



###########################################      BOOKS      ###################################################################


### Requição dos dados da tabela books

curl -X GET http://localhost:3000/books

### Requisição de Registro

curl -X POST http://localhost:3000/books -H "Content-Type: application/json" -d '{"title": "Isaías 54:17", "author": "Isaías", "price": "59.90"}'






